version: "3"
services:
    web:
        container_name: web
        build: .
        restart: always
        env_file:
            - .env
        volumes:
            - .:/holidayplanner
        ports:
            - 5000:5000
        depends_on:
            - db
    db:
        container_name: db
        image: postgres
        restart: always
        env_file:
            - .env
